### PR TITLE
community-details: add inline searchbar

### LINKED ISSUE #323: communities: top search is not redirecting to the global search
Package version (if known): 22.5

## Describe the bug
When you navigate to the communities details page and click on the top search bar, the results are refreshed in the communities page instead of redirecting in the global search page.

## Steps to Reproduce
1. Create a community e.g mycomid
2. Go to `/communities/mycomid`
3. See in the Search tab the demo records.
4. Click in the top search bar.
5. See the results refreshed internally.

## Expected behavior
We should redirect to the global search page, maybe similar to front page or make a proper search based on current community.

## Screenshots (if applicable)
Screenshot 2021-04-30 at 11 43 54

### LINKED ISSUE #558: community search: shared searchbar
Package version (if known): <version>

## Describe the bug
The main searchbar in community uploads is referring to community uploads, not to general search, therefore there is no way to reach the general search from the community uploads page directly.

## Expected behavior

The main search should be easily reachable from the community uploads search page

## Additional context

Solution 1: Override the default searchbar component in the community uploads search app 
the searchbar is using react portal to be rendered in the navbar, to display community uploads search bar above the search app it needs to be customized (check for example user dashboard uploads)
Pros: consistency with other views
Cons: 2 searchbars on one page

Solution 2:
Add "github" style searchbar selection option popping below the main searchbar after typing the search query phrase: "Search in all records" and "search in this community"

### PR DESCRIPTION
**Pull request by zzacharo**
closes #323
closes #558

# Screenshots

## Mobile
Screenshot 2022-05-02 at 10 00 05

## Tablet
Screenshot 2022-05-02 at 09 55 19

## Computer
Screenshot 2022-05-02 at 09 55 45

### CODE REVIEW

File: invenio_communities/assets/semantic-ui/js/invenio_communities/details_search/components.js [hunk 1]
```diff
@@ -124,11 +134,44 @@ export const CommunityRecordResultsGridItem = ({ result }) => {
...
-export const CommunityRecordSearchBarContainer = () => {
+export const CommunityRecordSearchAppLayout = (props) => {
+  const [sidebarVisible, setSidebarVisible] = React.useState(false);
+
   return (
-    <Overridable id={"SearchApp.searchbar"}>
-      <SearchBar />
-    </Overridable>
+    <Container>
+      <div className="rel-pt-2">
```
Comment (kpsherva) [inline invenio_communities/assets/semantic-ui/js/invenio_communities/details_search/components.js:142]:
```suggestion
    <Container className="rel-pt-2">
```

File: invenio_communities/assets/semantic-ui/js/invenio_communities/details_search/components.js [hunk 2]
```diff
@@ -124,11 +134,44 @@ export const CommunityRecordResultsGridItem = ({ result }) => {
   );
 };
 
-export const CommunityRecordSearchBarContainer = () => {
+export const CommunityRecordSearchAppLayout = (props) => {
```
Comment (kpsherva) [inline invenio_communities/assets/semantic-ui/js/invenio_communities/details_search/components.js:137]:
```suggestion
export const CommunityRecordSearchAppLayout = ({config, ...}) => {
```
to keep the interface clean

File: invenio_communities/assets/semantic-ui/js/invenio_communities/details_search/components.js [hunk 3]
```diff
@@ -124,11 +134,44 @@ export const CommunityRecordResultsGridItem = ({ result }) => {
...
+            <SearchBar
+              placeholder={i18next.t("Search records in community...")}
+            />
+          </Grid.Column>
+
+          <Grid.Row>
+            <GridResponsiveSidebarColumn
+              width={4}
+              open={sidebarVisible}
+              onHideClick={() => setSidebarVisible(false)}
```
Comment (kpsherva) [inline invenio_communities/assets/semantic-ui/js/invenio_communities/details_search/components.js:163]: IMO the sidebar should manage its own state (visible/hidden), not its parent

**Review by jennur — APPROVED** [review]

File: invenio_communities/assets/semantic-ui/js/invenio_communities/details_search/components.js (hunk 3 above)
Comment (jennur) [reply invenio_communities/assets/semantic-ui/js/invenio_communities/details_search/components.js:163]: I think that'll be tricky as the state is connected to the filter-button (line 145)?

Comment (zzacharo) [reply invenio_communities/assets/semantic-ui/js/invenio_communities/details_search/components.js:163]: The state is lifted because the sidebar is externally controlled...

**Review by kpsherva — APPROVED** [review]
