### PR TITLE
ul: provides visual feedback when changing permissions

### LINKED ISSUE #282: ux: save buttons missing visual feedback on success/failure
## Describe the bug

The save buttons on the community permissions pages have no visual feedback.

1. You cannot see you have changed a value and if it was saved or not
2. Once you click save, the user has no feedback if it was success or failure.

## Expected behavior

Option 1: Save button starts out in disabled state. If the user changes a dropdown it becomes enabled. They can then click save, and it goes back to disabled state on success.

Option 2: Once an operation was a success, display a small message green text message for a couple of seconds that that says "Saved".

## Screenshots (if applicable)

Screenshot 2021-04-27 at 21 19 49

### PR DESCRIPTION
**Pull request by Glignos**
* Closes #282

### CODE REVIEW

**Comment by Glignos** [comment]
https://user-images.githubusercontent.com/16304052/116671447-3b9e7000-a9a1-11eb-8903-f4431c27a372.mov

File: invenio_communities/assets/semantic-ui/js/invenio_communities/settings/privileges.js [hunk 1]
```diff
@@ -36,18 +37,23 @@ class CommunityPrivilegesForm extends Component {
...
         onSubmit={async (
           values,
-          { setSubmitting, setErrors, setFieldError }
+          { setSubmitting, setErrors, setFieldError, setIsActive }
         ) => {
           setSubmitting(true);
           const payload = values;
           try {
-            await axios.put(
+            axios.put(
```
Comment (zzacharo) [inline invenio_communities/assets/semantic-ui/js/invenio_communities/settings/privileges.js:56]: Use `await` here :) You don't need the `.then()` as that syntax is used for Promises...

File: invenio_communities/assets/semantic-ui/js/invenio_communities/settings/privileges.js [hunk 2]
```diff
@@ -57,9 +63,12 @@ class CommunityPrivilegesForm extends Component {
...
                 withCredentials: true,
               }
-            );
-            setSubmitting(false);
-            window.location.reload();
+            )
+            .then( r => {
+                setSubmitting(false);
+                this.setIsSavedState(true);
+                console.log(isSaved)
```
Comment (zzacharo) [inline invenio_communities/assets/semantic-ui/js/invenio_communities/settings/privileges.js:70]: leftover :)

File: invenio_communities/assets/semantic-ui/js/invenio_communities/settings/privileges.js [hunk 3]
```diff
@@ -117,8 +127,10 @@ class CommunityPrivilegesForm extends Component {
                   icon
                   labelPosition="left"
                   loading={isSubmitting}
+                  toggle
+                  active={isSaved}
                 >
-                  <Icon name="save"></Icon>Save
+                  <Icon name="save"></Icon>{isSaved ?'Saved': 'Save'}
```
Comment (zzacharo) [inline invenio_communities/assets/semantic-ui/js/invenio_communities/settings/privileges.js:133]: Maybe the `Saved` text should be shown for a limited amount of time and then go back to `Save` ? I am thinking about the case that the user saves, then button becomes Saved but then they want to change the value again so they will need to click on the `Saved` button for saving again....I think it feels a bit weird from UX perspective...

File: invenio_communities/assets/semantic-ui/js/invenio_communities/settings/privileges.js [hunk 4]
```diff
@@ -36,18 +37,23 @@ class CommunityPrivilegesForm extends Component {
...
+
   render() {
+    const { isSaved } = this.state
     return (
       <Formik
         initialValues={this.getInitialValues(this.props.community)}
         onSubmit={async (
           values,
-          { setSubmitting, setErrors, setFieldError }
+          { setSubmitting, setErrors, setFieldError, setIsActive }
```
Comment (zzacharo) [inline invenio_communities/assets/semantic-ui/js/invenio_communities/settings/privileges.js:51]: Is `setIsActive` used?

File: invenio_communities/assets/semantic-ui/js/invenio_communities/settings/privileges.js (hunk 3 above)
Comment (Glignos) [reply invenio_communities/assets/semantic-ui/js/invenio_communities/settings/privileges.js:133]: but this will change to save as soon as they change a value.

**Review by zzacharo — APPROVED** [review]
